// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbhcrbxatcvgfbuibzrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpiaGNyYnhhdGN2Z2ZidWlienJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNjE2NzcsImV4cCI6MjA2MzczNzY3N30.AJ-JS_KewhQrr6zQJyTlU70fFJzuvu5TfhwCbki9pz8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);